[package]
name = "mod_traffic"
version = "0.1.0"
edition = "2021"

[dependencies]
aether_traits = { path = "../../crates/aether_traits" }
async-trait = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }

[lib]
path = "src/lib.rs"
