[package]
name = "aether_traits"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }

[lib]
path = "src/lib.rs"
